# Site settings
title: Hi! I am Clare! ğŸ‘‹ğŸ¼
name: Clare So
email: melsong@duck.com
url: https://clarmso.ca
description: "Clare So's Homepage'"
keywords: "software test engineer"
skills: "Software Test Engineer"
about: "Write code to test software. Based in Kitchener-Waterloo ON. ğŸ‡¨ğŸ‡¦ May play piano from home before the meetings. ğŸ¹ Prefer open source software. Bragging rights include breaking software by a donut emoji. ğŸ©"
meta_author: "Clare So"

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
# contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: FD6E8A #18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Clare So
  social: Around the Web

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/clarmso
  - title: instagram
    url: https://www.instagram.com/clarmso
  - title: mastodon
    url: https://mastodon.online/@clarmso
  - title: linkedin
    url: https://www.linkedin.com/in/clarmso
  - title: github
    url: https://github.com/clarmso

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
